version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_tutor_sg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      # If you prefer DATABASE_URL, ensure settings reads it
      # DATABASE_URL: postgres://postgres:postgres@db:5432/ai_tutor_sg
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost/api}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
