# Generated by Django 5.2.7 on 2025-10-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Mathematics'), ('Science', 'Science'), ('English', 'English')], max_length=20)),
                ('level', models.CharField(choices=[('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6'), ('Sec1', 'Secondary 1'), ('Sec2', 'Secondary 2'), ('Sec3', 'Secondary 3'), ('Sec4', 'Secondary 4')], max_length=10)),
                ('question_text', models.TextField()),
                ('is_multiple_choice', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('flag_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['subject', 'level'], name='quiz_questi_subject_85e8b4_idx')],
            },
        ),
    ]
